from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from .ide import IDEController


@dataclass(frozen=True)
class QualityResult:
    ruff_ok: bool
    pytest_ok: bool
    ruff_out: str
    pytest_out: str


class QualityGate:
    def __init__(self, ide: IDEController) -> None:
        self.ide = ide

    def run_ruff(self) -> tuple[bool, str]:
        code, out, err = self.ide.run_task_like("python -m ruff check . --fix && python -m ruff format .", timeout_sec=900)
        txt = (out + "\n" + err).strip()
        ok = code == 0
        return ok, txt

    def run_pytest(self) -> tuple[bool, str]:
        code, out, err = self.ide.run_task_like("python -m pytest -q", timeout_sec=900)
        txt = (out + "\n" + err).strip()
        ok = code == 0 and ("FAILED" not in txt) and ("ERROR" not in txt)
        return ok, txt

    def extract_fail_summary(self, pytest_out: str) -> str:
        # lightweight: keep last 200 lines
        lines = pytest_out.splitlines()[-200:]
        return "\n".join(lines)

    def apply_unified_diff(self, workspace_root: Path, diff_text: str) -> list[Path]:
        """
        Apply a unified diff generated by DEV agent.
        This implementation supports file replace by parsing '--- a/..' '+++ b/..' and hunks.
        For robustness, we restrict to full-file replace if the diff contains 'FREYA_FULLFILE:' blocks.
        """
        # Safer protocol: DEV outputs blocks:
        # FREYA_FULLFILE: relative/path.py
        # ```python
        # <full content>
        # ```
        changed: list[Path] = []
        pattern = r"FREYA_FULLFILE:\s*(.+?)\n```(?:\w+)?\n(.*?)\n```"
        matches = re.findall(pattern, diff_text, flags=re.DOTALL)
        if not matches:
            raise ValueError("No FREYA_FULLFILE blocks found. DEV must output fullfile blocks.")

        for rel, content in matches:
            rel = rel.strip().replace("\\", "/")
            if rel.startswith("../") or rel.startswith("..\\"):
                raise PermissionError("Path traversal blocked")
            p = (workspace_root / Path(rel)).resolve()
            if workspace_root not in p.parents and p != workspace_root:
                raise PermissionError(f"Outside workspace blocked: {p}")
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            changed.append(p)
        return changed
