from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from .ide import IDEController


@dataclass(frozen=True)
class QualityResult:
    ruff_ok: bool
    pytest_ok: bool
    ruff_out: str
    pytest_out: str


class QualityGate:
    def __init__(self, ide: IDEController) -> None:
        self.ide = ide

    def run_ruff(self) -> tuple[bool, str]:
        code, out, err = self.ide.run_task_like("python -m ruff check . --fix && python -m ruff format .", timeout_sec=900)
        txt = (out + "\n" + err).strip()
        ok = code == 0
        return ok, txt

    def run_pytest(self) -> tuple[bool, str]:
        code, out, err = self.ide.run_task_like("python -m pytest -q", timeout_sec=900)
        txt = (out + "\n" + err).strip()
        ok = code == 0 and ("FAILED" not in txt) and ("ERROR" not in txt)
        return ok, txt

    def extract_fail_summary(self, pytest_out: str) -> str:
        # lightweight: keep last 200 lines
        lines = pytest_out.splitlines()[-200:]
        return "\n".join(lines)

    def apply_unified_diff(self, workspace_root: Path, diff_text: str) -> list[Path]:
        """
        Apply code blocks generated by DEV agent.
        
        Supports multiple formats:
        1. FREYA_FULLFILE: path/file.py
           ```python
           content
           ```
        2. ```python filename="path/file.py"
           content
           ```
        3. # File: path/file.py
           ```python
           content
           ```
        """
        changed: list[Path] = []
        
        # Pattern 1: FREYA_FULLFILE: path
        pattern1 = r"FREYA_FULLFILE:\s*(.+?)\n```(?:\w+)?\n(.*?)\n```"
        matches = re.findall(pattern1, diff_text, flags=re.DOTALL)
        
        # Pattern 2: ```lang filename="path"
        if not matches:
            pattern2 = r"```(?:\w+)?\s+filename=[\"'](.+?)[\"']\n(.*?)\n```"
            matches = re.findall(pattern2, diff_text, flags=re.DOTALL)
        
        # Pattern 3: # File: path followed by code block
        if not matches:
            pattern3 = r"#\s*File:\s*(.+?)\n```(?:\w+)?\n(.*?)\n```"
            matches = re.findall(pattern3, diff_text, flags=re.DOTALL)
        
        # Pattern 4: **path** or `path` followed by code block  
        if not matches:
            pattern4 = r"(?:\*\*|`)([a-zA-Z0-9_./\\-]+\.(?:py|js|ts|tsx|json|md|html|css|yaml|yml))(?:\*\*|`)\s*\n```(?:\w+)?\n(.*?)\n```"
            matches = re.findall(pattern4, diff_text, flags=re.DOTALL)
        
        # Pattern 5: Just look for any code blocks and infer filenames
        if not matches:
            # Find all code blocks with language hints
            code_blocks = re.findall(r"```(\w+)\n(.*?)\n```", diff_text, flags=re.DOTALL)
            for i, (lang, content) in enumerate(code_blocks):
                ext_map = {'python': 'py', 'javascript': 'js', 'typescript': 'ts', 'json': 'json', 'html': 'html', 'css': 'css'}
                ext = ext_map.get(lang.lower(), lang.lower())
                if ext in ('py', 'js', 'ts', 'tsx', 'json', 'html', 'css', 'yaml', 'yml'):
                    filename = f"generated_{i+1}.{ext}"
                    matches.append((filename, content))
        
        if not matches:
            # Log the raw output for debugging
            import logging
            logging.getLogger("freya.quality").warning(f"No code blocks found in DEV output. Raw output (first 500 chars):\n{diff_text[:500]}")
            # Return empty instead of raising - the log will help debug
            return []

        for rel, content in matches:
            rel = rel.strip().replace("\\", "/")
            # Remove leading slashes or dots
            while rel.startswith("/") or rel.startswith("./"):
                rel = rel.lstrip("/").lstrip("./")
            if rel.startswith("../") or rel.startswith("..\\"):
                continue  # Skip path traversal attempts
            if not rel:
                continue
            
            p = (workspace_root / Path(rel)).resolve()
            try:
                if workspace_root.resolve() not in p.parents and p != workspace_root.resolve():
                    continue  # Skip files outside workspace
            except (ValueError, OSError):
                continue
            
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            changed.append(p)
        
        return changed
